server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://106.14.182.139:3306/demo?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver